spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
# Example Thymeleaf Configuration in application.yml
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false # Disable caching for development

